# Generated by Django 3.2.7 on 2021-10-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
