# Generated by Django 3.2.7 on 2021-10-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='has_module_perms',
        ),
    ]
