# Generated by Django 3.2.7 on 2021-10-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidate',
            table='candidates',
        ),
        migrations.AlterModelTable(
            name='election',
            table='elections',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='votes',
        ),
    ]
