# Generated by Django 3.2.7 on 2021-10-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20211020_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(default='YEZR29H6PR', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_id',
            field=models.CharField(default='KODAFRJUQJ', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
