# Generated by Django 3.2.7 on 2021-10-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_auto_20211020_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(default='24V03TQQ0J', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='election',
            name='candidates',
        ),
        migrations.AddField(
            model_name='election',
            name='candidates',
            field=models.ManyToManyField(related_name='election', to='elections.Candidate'),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_id',
            field=models.CharField(default='DFJROA0S3T', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
