# Generated by Django 3.2.7 on 2021-10-20 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elections', '0004_auto_20211020_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(default='N54DBL4G2J', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_id',
            field=models.CharField(default='4OEGSQKG80', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
